### ISSUE TITLE
Use of RELEASE breaks some proxies

### ISSUE THREAD

**Issue by SevereOverfl0w** [lambdaisland/kaocha-cljs#29]
The proxy I use at work (not sure what it is) does not support release.

These aren't supported anymore anyway:https://cwiki.apache.org/confluence/display/MAVEN/Maven+3.x+Compatibility+Notes#Maven3.xCompatibilityNotes-PluginMetaversionResolution

**Comment by plexus** [comment]
Thanks for reporting. This wasn't intended to be released like this.
