### ISSUE TITLE
Need to pass cljs compiler options

### ISSUE THREAD

**Issue by chadharrington** [lambdaisland/kaocha-cljs#7]
I need to pass custom options to the cljs compiler, specifically :npm-deps and :optimizations. It would be great to have an option to handle this from tests.edn, probably by pointing to a cljs-opts.edn file.

**Comment by plexus** [comment]
Hi @chadharrington , you can use the `:cljs/compiler-options` option. You can read in a file with Aero's `#include`.

**Comment by chadharrington** [comment]
Thanks for the tip. I am able to use Aero's include, and the compiler options show up in the --print-config output. However, the options don't seem to affect the compilation. I think there is still an issue here. I will debug further and reopen if I can provide a minimal reproduction.
