### ISSUE TITLE
Remove Websocket requirement?

### ISSUE THREAD

**Issue by nwjsmith** [lambdaisland/kaocha-cljs#8]
First of all: thank you for kaocha-cljs, I had this magical experience yesterday where I [hooked it up to my Clojure project](https://github.com/nwjsmith/generators.graph/commit/3b3eec08bda32fa62971c4acd0403de01fbcadb9), renamed files from `clj` -> `cljc` and everything Just Worked™️.

I was wondering is if you would be interested in having the Websocket dependency removed? If I'm understanding [this comment of yours](https://github.com/lambdaisland/kaocha-cljs/issues/2#issuecomment-457449711) correctly, then it seems like HTTP long-polling would be a good fit and something that works on Node.JS, Nashorn, and in-browser.

**Comment by plexus** [comment]
I certainly didn't mean to imply we should drop the websocket. If someone wants to replace it with something equivalent that works equally well and is available on more platforms then of course that's welcome.

**Comment by nwjsmith** [comment]
@plexus Haha I worded my comment weirdly, you didn't imply dropping the websocket. Since you're open to the idea I'll try to work out something that can work on all the platforms without further dependencies. Thanks for following up!
